### ISSUE TITLE
Add a README and some documentation with how to

### ISSUE THREAD

**Issue by lisachenko** [goaop/goaop-symfony-bundle#1]
Need to have a documentation for bundle with config description and several examples of realization of logging, etc.

**Comment by jost125** [comment]
And is it already working? I would be very pleased to test it, but unfortunately without docs it is quite hard to make it works on my own ;-)

**Comment by lisachenko** [comment]
Hello, @jost125. I can confirm that it's working now, but without cache warming ( I planned to work on docs earlier, but without success, there is no free time at all. So, now it's "as-is" ) However things can be changed in any time, so just watch this repo for notifications.

**Comment by jost125** [comment]
Sure, thx for info

**Comment by lisachenko** [comment]
Docs are ready, hope this will help to start use this bundle. Also cache warming is fixed now.

**Comment by jost125** [comment]
Great! I will test it and let you know if we hit any problem :)
