### ISSUE TITLE
goaop bundle + composer optimize autoloader

### ISSUE THREAD

**Issue by alexbumbacea** [goaop/goaop-symfony-bundle#12]
If you install the app with composer and optimize autoloader, the interceptors are not loaded (it loads the normal class).

**Comment by lisachenko** [comment]
Which version of PHP do you use? And one more question: could you check in your vendor/composer directory paths in files: are they relative?

Could be related to the https://github.com/goaop/framework/pull/295...

**Comment by TheCelavi** [comment]
@alexbumbacea Is this issue resolved, do you still experience same issue? If not, would you mind closing the issue?

**Comment by TheCelavi** [comment]
@alexbumbacea Thank you!
