### ISSUE TITLE
Doesnt work in NON-Debug mode - no errors reported

### ISSUE THREAD

**Issue by atompulse** [goaop/goaop-symfony-bundle#13]
Hi there!
I'm encountering a weird issue where the aop doenst work if the application is started in non-debug mode: 

**doesnt work**: `$kernel = new AppKernel('prod', false)`
**it works**: `$kernel = new AppKernel('prod', true);`

Any ideas or tips on what is going on in here?
Should I check something specifically in my configs or is this a bug?

And there are no errors, the proxy classes are all created ok, everything seems to be in place, it's just that the AOP doesnt trigger.

Symfony version: 2.8.16
PHP version: 5.6.27

**Comment by atompulse** [comment]
Any ideas? I'm in very bad position and had investigated the code but cant figure out the issue...

**Comment by atompulse** [comment]
News: I tested with plain simple symfony demo app 3.2 (without any of my dependencies and code, wanted to make sure there's no hidden red herings) and I can confirm the issue is consistent:
- if kernel is not in debug mode, the aop doesnt work, fails silently, no errors emited, although proxy classes are correctly generated and in place
-if kernel is in debug mode, everything works as expected

Sample aspect I'm using for test:

```
<?php
namespace AppBundle\Aop;

use Go\Aop\Aspect;
use Go\Aop\Intercept\MethodInvocation;
use Go\Lang\Annotation\Before;
use Symfony\Component\DependencyInjection\ContainerAwareTrait;

/**
 * Class Signal
 * @package AppBundle\Aop
 *
 */
class Signal  implements Aspect
{
    use ContainerAwareTrait;

    /**
     * @param MethodInvocation $invocation
     * @Before("execution(public AppBundle\Controller\BlogController->postShowAction(*))")
     */
    public function beforeMethod(MethodInvocation $invocation)
    {
        $this->container->get('logger')->error('-----executed signal-----');
    }
}
```

**config.yml**
```
go_aop:
    cache_warmer: true
    options:
        debug: %kernel.debug%
        app_dir: "%kernel.root_dir%/../src/"
        cache_dir: %kernel.cache_dir%/aspect
        include_paths: ["%kernel.root_dir%/../src/AppBundle/Controller"]
        exclude_paths: []
        features: []
```

**services.yml**

```
    signal.aspect:
      class:  AppBundle\Aop\Signal
      calls:
        - [setContainer, ['@service_container']]
      tags:
        - { name: goaop.aspect }
```

**Comment by lisachenko** [comment]
Hi! From your issue it's unclear which aspects do you use, what is your version of `goaop/framework` and `goaop/goaop-symfony-bundle` itself?

It's very hard to guess, why it isn't working. Just several points to check: 

- do you use inlining of classes in your bundle (eg. classes.php) or not.
- put a breakpoint into the `GoAopBundle->boot()` method. Is it called or not? If not, then AOP is not initialized, but it's very strange.

**Comment by atompulse** [comment]
First of all, thanks for the suggestions.

Related to versions:
`"symfony/symfony": "^3.2"`
`"goaop/goaop-symfony-bundle": "2.*"`

I already tried the breakpoint at boot and in many other places, I can confirm the bundle is successfully booted, again it works perfectly when in debug mode `(i.e. $kernel = new AppKernel('prod', **true**); )`
About the inlining of classes I'm not sure what you mean, every class is in its own file; you can see the example I'm giving above with the default symfony 3.2 blod demo app.

From what I learned up to this point, it seems very possible that there's a problem related to loading the classses in debug mode vs non-debug mode.
Using XDebug I can see that when using kernel debug mode the proxy classes are used, but not when using the non-debug mode, although the bundle is correctly loaded and all the rest.

**Comment by lisachenko** [comment]
> About the inlining of classes I'm not sure what you mean, every class is in its own file; you can see the example I'm giving above with the default symfony 3.2 blog demo app.

I was referring to the [adding classes to the compiled cache](http://symfony.com/doc/current/bundles/extension.html#adding-classes-to-compile) technique.

Anyway, if each single class in it's own file and standard autoloader is used then everything should work. I'll try to reproduce your issue myself. Looks like this can be related to the mapping relative paths from the composer to real one.

Last check: could you please install `goaop/framework` from the master branch to be sure, that this issue isn't fixed yet in the framework

**Comment by atompulse** [comment]
Installed version for framework is `2.0.0`
Should i try a different version?

**Comment by lisachenko** [comment]
>Installed version for framework is 2.0.0
Should i try a different version?

Yes, please: `composer require goaop/framework:2.0.x-dev`

**Comment by atompulse** [comment]
Hi @lisachenko ,
I forced the `oaop/framework:2.0.x-dev` usage and indeed the issue vanished.

Could you please push this fix to the stable release? It should stop people getting into the same problem that I did.

Anyways, thank you for your support and awesome work on this library.

Cheers!

**Comment by lisachenko** [comment]
Hi, @atompulse! Thank you for checking, I will prepare a tag then (probably on weekends, need to recheck all issues).

For now, you could use dev-version for short period of time.

Thank you for issue reporting!

**Comment by lisachenko** [comment]
Version 2.1.0 is released. Now you can switch to the stable tag. Thank you!

**Comment by atompulse** [comment]
@lisachenko Thank you!
👍
