### ISSUE TITLE
Add a tests and travis-ci integration for good code quality

### ISSUE THREAD

**Issue by lisachenko** [goaop/goaop-symfony-bundle#2]

**Comment by TheCelavi** [comment]
One of two - done. You could add travis-ci integration....

**Comment by TheCelavi** [comment]
Added in PR: https://github.com/goaop/goaop-symfony-bundle/pull/16, will close issue when PR is merged.

**Comment by lisachenko** [comment]
Enabled Travis-CI integration, should be triggered during the next push or PR update

**Comment by lisachenko** [comment]
Fixed in #16.
Tests were added, Travis-CI and Scrutinizer-CI were configured. Thanks to @TheCelavi !
