### ISSUE TITLE
Minimum-Stability needs to be set to "dev"

### ISSUE THREAD

**Issue by cawolf** [goaop/goaop-symfony-bundle#25]
Thank you for the great bundle. Currently, the usage of "roave/security-advisories" prevents us from using the bundle as the `minimum-stability` needs to be set to "dev".

Can you please move the dependency to `require-dev` so that we don't need to tinker our `minimum-stability`? Thank you very much! :)

**Comment by lisachenko** [comment]
Hi! Nice catch with `dev` section, could you send a PR for that, I'll be happy to merge it

**Comment by cawolf** [comment]
I just opened PR #26 to solve this issue.

**Comment by cawolf** [comment]
Thanks for merging! Do you already know when you will release the next version?

**Comment by TheCelavi** [comment]
@lisachenko can give you that answer, I do not see any reason not to release bumped minor version.

**Comment by lisachenko** [comment]
Sorry, guys, busy at work. Releasing next version is perfectly ok, will do this now...
