### ISSUE TITLE
Question about pointcut syntax for matching method in the class

### ISSUE THREAD

**Issue by xocasdashdash** [goaop/goaop-symfony-bundle#7]
Hi!
I'm having some problems with the syntax if I use a very simple regex:
`@Before("execution(public **->addDeal(*))")`
It works, but I would like to narrow it down a little bit more, so addDeal is a method of the class
AbstractDealGroupingModel but if i write this down
`@Before("execution(public AbstractDealGroupingModel->addDeal(*))")`
it never get executed. Is there something wrong with the syntax that I'm using?

**Comment by lisachenko** [comment]
Hi, probably you forgot about the namespace? Is you class `AbstractDealGroupingModel` in top-level namespace or not?

BTW, if you are using PhpStorm, then install "Go! AOP Framework" plugin that will show you when method is intercepted, as well as pointcut syntax and autocompletion.

**Comment by xocasdashdash** [comment]
ohhh Ok ok, now I see it working :) 
How big is the performance impact of using the different aspect types?

**Comment by lisachenko** [comment]
For production mode with PHP7, AOP adds 5-10ms extra time for initialization and 1-2ms for method interception plus time for class loading checks. So for real cases this should be about 5-100ms, depending of your application size and AOP usage.

Best way is just to try this yourself with your aspects ;) And measure time for method without AOP and with enabled AOP

**Comment by lisachenko** [comment]
Closed )
