### ISSUE TITLE
You have requested a non-existent service "goaop.aspect.container".

### ISSUE THREAD

**Issue by ncrypthic** [goaop/goaop-symfony-bundle#8]
When I added this bundle into my project, everything works fine in dev environment, but when I try to run in production I hit this `ServiceNotFoundException`. When I try to clear the cache, it also throws the same exception.

I try to dig around the problem and found that the exception was trigger by [GoAopBundle:50](https://github.com/goaop/goaop-symfony-bundle/blob/master/GoAopBundle.php#L48).

This is because Symfony tries to boot existing bundles found in the configuration before clearing it caches. But when it tries to boot GoAopBundle it couldn't find `goaop.aspect.containter` service because it wasn't there in previous cache.

My work around is to clear the cache manually, by removing it folder. Then executes `cache:warmup` using Symfony console.

**Comment by TheCelavi** [comment]
Closed as general, known issue of SF applications when cache gets corrupted. Workaround is appropriate, deleting cache manually will solve issue.
